---
- name: Create logging.d config directory
  file: path=/etc/newrelic-infra/logging.d state=directory mode=0755
  when:
    - nrinfragent_logging is defined
    - nrinfragent_state != "absent"
    - nrinfragent_os_name != 'windows'

- name: Setup logging
  template:
    src: newrelic-logging.yml.j2
    dest: /etc/newrelic-infra/logging.d/logging.yml
    trim_blocks: no
  when:
    - nrinfragent_logging is defined
    - nrinfragent_state != "absent"
    - nrinfragent_os_name != 'windows'

- name: setup logging (windows)
  win_template:
    src: newrelic-logging.yml.j2
    dest: C:\Program Files\New Relic\newrelic-infra\logging.d\logging.yml
    trim_blocks: no
  when:
    - nrinfragent_logging is defined
    - nrinfragent_state != "absent"
    - nrinfragent_os_name == 'windows'
